[profile.default]
evm_version = 'prague'
hardfork = 'amsterdam'
gas_limit = 'max'
src = 'src'
out = 'out'
ffi = true
libs = ['lib']
fs_permissions = [{ access = "read", path = "./bytecode" }, { access = "read", path = "./test" }]