name: test

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build bytecode
        run: |
          make build
        id: build
      - name: Run tests
        run: |
          make test
        id: test
